require("nvim-treesitter.configs").setup {
    ensure_installed = {
        "lua",
        "luadoc",
        "c",
        "cpp",
        "cmake",
        "qmljs",
        "blueprint",
        "rust",
        "ron",
        "python",
        "regex",
        "html",
        "css",
        "scss",
        "javascript",
        "jsdoc",
        "typescript",
        "tsx",
        "nix",
        "bash",
        "make",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
        "toml",
        "json",
        "jsonc",
        "hyprlang",

        "markdown",
        "markdown_inline",
        "latex",
        "diff",

        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
    },

    sync_install = false,

    auto_install = false,

    highlight = {
        enable = true,
    },
}
