return {
    "windwp/nvim-ts-autotag",
    event = "VeryLazy",
    ft = {
        "astro",
        "glimmer",
        "handlebars",
        "html",
        "javascript",
        "jsx",
        "markdown",
        "php",
        "rescript",
        "svelte",
        "tsx",
        "twig",
        "typescript",
        "vue",
        "xml",
    },
    opts = {},
}
